name: Industrial CI pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, UP, UPSTREAM_WORKSPACE: file, ROSINSTALL_FILENAME: .ci.rosinstall}
    steps:
      - uses: actions/checkout@v1
      - uses: 'ipa-mdl/industrial_ci@github-action'
        env: ${{matrix.env}}
